Plantilla de Pre Procesado

In [1]:
# Cómo importar las librerías
import numpy as np
import matplotlib.pyplot as  plt
import pandas as pd

In [2]:
# Importar el data set
%cd "D:\Repos Github\machinelearning-az\update\Part 1 - Data Preprocessing\Section 2 -------------------- Part 1 - Data Preprocessing --------------------/Python"
dataset = pd.read_csv('Data.csv')

D:\Repos Github\machinelearning-az\update\Part 1 - Data Preprocessing\Section 2 -------------------- Part 1 - Data Preprocessing --------------------\Python


In [3]:
dataset.head()


Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [4]:
#Variable independiente = columnas Country + Age+ Salary 
#Variable dependiente = columna Purchased
X = dataset.iloc[:,:-1].values 
#Todas las filas y todas las columnas salvo la última
#.values porque queremos extraer los valores, no las posiciones


In [5]:
y= dataset.iloc[:,3].values #Selecciona tercera columna 

In [7]:
# Tratamiento de los NAs
from sklearn.impute import SimpleImputer #Como no queremos toda la librería sino sólo una parte. Imputer calcula los datos faltantes (NAs
# Ahora creamos un objeto de esta clase (Imputer)
imputer = SimpleImputer(missing_values=np.nan,strategy="mean") #missing_values=np.nan puedo no ponerlo
#strategy -> cómo voy a sustituir los valores desconocidos. En este caso media
imputer.fit(X[:, 1:3])  # Aplicamos el ajuste a las columnas 1 y 2 (índices 1:3 porque el último no lo coge)
X[:, 1:3] = imputer.transform(X[:, 1:3])  # Reemplazamos los valores nulos en las columnas seleccionadas. Tb vale imputer.fit_transform
print("Datos de X después de manejar valores faltantes:")
print(X)

Datos de X después de manejar valores faltantes:
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [8]:
# Codifcar datos categóricos
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [15]:
#Aplicamos OneHotEncoder a primera columna (0)
ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(),[0])],
    remainder='passthrough'
)
#ColumnTransformer([...], remainder='passthrough')
# significa Aplica distintos transformadores a columnas concretas y decide qué hacer con el resto:
#La lista transformers=[('encoder', OneHotEncoder(), [0])] 
# dice: “aplica el OneHotEncoder a la columna 0”
# remainder='passthrough' significa: las demás columnas se mantienen sin tocar
X=np.array(ct.fit_transform(X))
# fit: el encoder aprende qué categorías existen y en qué orden.
# transform: genera la matriz codificada y concatena las columnas restantes.
# Transformamos X y lo convertimos a un array de NumPy
print("Datos de X después de la codificación OneHot:")
print(X)

Datos de X después de la codificación OneHot:
[[1.0 0.0 1.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 1.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 35.0 58000.0]
 [0.0 1.0 0.0 1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 37.0 67000.0]]


In [16]:
# Codificación de la variable dependiente (y)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)  # Transformamos las etiquetas categóricas en valores numéricos
print("Datos de y después de la codificación:")
print(y)

Datos de y después de la codificación:
[0 1 0 0 1 1 0 1 0 1]


In [ ]:
# Dividir el data set en conjunto de entrenamiento y conjunto de testing

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
# x= variable independiente
# y= variable dependiente
# test_size =0.2 eserva ~20% de las filas para test y ~80% para train (redondea a un entero según el tamaño del dataset)
# random_state=0 → fija la semilla del aleatorizador para que la misma partición se repita cada vez que ejecutes el código (reproducibilidad).
# Devuelve:
# X_train y y_train: datos para entrenar el modelo
# X_test y y_test: datos nunca vistos que usarás para evaluar el modelo.
# En clasificación, añade stratify=y para mantener la misma proporción de clases en train y test:

In [21]:
X_train

array([[0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 37.0, 67000.0],
       [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [25]:
#Escalado de variables

# Estandarizamos los valores para que tengan media 0 y desviación estándar 1. Valores entre -1 y 1
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])  # Ajustamos y transformamos las características numéricas del conjunto de entrenamiento
X_test[:, 3:] = sc.transform(X_test[:, 3:])  # Transformamos el conjunto de prueba usando el ajuste del conjunto de entrenamiento
print("Conjunto de entrenamiento después del escalado de características:")
print(X_train)
print("Conjunto de prueba después del escalado de características:")
print(X_test)

Conjunto de entrenamiento después del escalado de características:
[[0.0 1.0 0.0 1.0 -1.0 2.6457513110645907 -0.7745966692414833
  0.26306757317135365 0.12381478548381816]
 [1.0 0.0 1.0 -1.0 1.0 -0.37796447300922714 -0.7745966692414833
  -0.2535014796014863 0.46175631762788527]
 [0.0 1.0 0.0 1.0 -1.0 -0.37796447300922714 1.2909944487358056
  -1.9753983221776197 -1.5309334063940299]
 [0.0 1.0 0.0 1.0 -1.0 -0.37796447300922714 1.2909944487358056
  0.052613514634270886 -1.111419780284153]
 [1.0 0.0 1.0 -1.0 1.0 -0.37796447300922714 -0.7745966692414833
  1.6405850472322603 1.7202971959575157]
 [0.0 1.0 0.0 1.0 -1.0 -0.37796447300922714 1.2909944487358056
  -0.08131179534387295 -0.16751412153693]
 [1.0 0.0 1.0 -1.0 1.0 -0.37796447300922714 -0.7745966692414833
  0.9518263102018071 0.9861483502652313]
 [1.0 0.0 1.0 -1.0 1.0 -0.37796447300922714 -0.7745966692414833
  -0.5978808481167129 -0.4821493411193376]]
Conjunto de prueba después del escalado de características:
[[0.0 1.0 0.0 1.0 -1.0 2.6